Add Plain endpoints to docs
teal-dev/docs pull request #19
Opened 2023-09-21 22:16 UTC by alejom99

2023-09-21 23:41 UTC, frayecam requested changes

2023-09-21 23:41 UTC, frayecam commented on api-reference/transaction_sources/get_plaid_link_status.mdx
How does this work? It only takes a bear token. I assume it returns all Plaid connected financial account ledgers for the entire platform (could be 1000s)? If so, we should update the description to: 
"Returns the status of all Plaid connected financial account ledgers on the platform"

2023-09-21 23:41 UTC, frayecam commented on api-reference/transaction_sources/link_plaid_account.mdx
I don't think the description makes sense here. We aren't linking an existing ledger to a Plaid account. Rather, we are creating a new financial account ledger and linking it. We should update the description to: 
"Link an external financial account via Plaid. This endpoint will create a new financial account ledger in the user's chart of accounts and link Plaid as the datasource."

2023-09-22 00:14 UTC, thomaschisholm commented on api-reference/transaction_sources/get_plaid_link_status.mdx
Yes it is for the whole platform. The platform id is read from the token.

2023-09-22 00:24 UTC, frayecam approved these changes

2023-09-22 00:28 UTC, merged